export const DEVICE_FETCH = "DEVICE_FETCH";
export const DEVICE_LOAD = "DEVICE_LOAD";
export const DEVICE_FAILED = "DEVICE_FAILED";
export const DEVICE_SELECT = "DEVICE_SELECT";
export const DEVICE_MODAL_OPEN = "DEVICE_MODAL_OPEN";
export const DEVICE_MODAL_CLOSE = "DEVICE_MODAL_CLOSE";
