export const MANUFACTURER_FETCH = "MANUFACTURER_FETCH";
export const MANUFACTURER_LOAD = "MANUFACTURER_LOAD";
export const MANUFACTURER_FAILED = "MANUFACTURER_FAILED";
export const MANUFACTURER_SELECT = "MANUFACTURER_SELECT";
