#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

export NVM_DIR="$HOME/.nvm/nvm.sh"
. "$(dirname $NVM_DIR)/nvm.sh"

export NVM_DIR="$HOME/.nvm"
a=$(nvm ls | grep 'node')
b=${a#*(-> }
v=${b%%[)| ]*}
export PATH="$NVM_DIR/versions/node/$v/bin:$PATH"

FILES=$(git diff --cached --name-only --diff-filter=ACMR | sed 's| |\\ |g')
[ -z "$FILES" ] && exit 0

# Prettify all selected files
npx prettier --ignore-unknown --write $FILES 
npm run translate 1>/dev/null
LIST="puts\|debugger\|binding.pry\|console.log("

# Add back the modified/prettified files to staging
echo "$FILES" | xargs git add

ls -1 -d "$PWD"/src/locales/*/*.json | xargs git add

exit 0
