#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

if git rev-parse --verify HEAD >/dev/null 2>&1; then
    against=HEAD
else
    against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
fi
FILES=`git diff-index --name-status --cached $against -- | cut -c3-`
[ -z "$FILES" ] && exit 0

# Prettify all selected files
npx prettier --ignore-unknown --write $FILES 
npx i18next 'src/**/*.{tsx,ts}' 1>/dev/null
LIST="puts\|debugger\|binding.pry\|console.log("


for FILE in $FILES ; do
    # Check if the file contains one of the words in LIST
    if grep -w $LIST $FILE; then
      echo $FILE." has one of the word you don't want to commit. Please remove it"
      exit 1
    fi
      done

# Add back the modified/prettified files to staging
echo "$FILES" | xargs git add

ls -1 -d "$PWD"/src/locales/*/*.json | xargs git add

exit 0
